# Generated by Django 4.2.1 on 2023-05-26 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strength', models.IntegerField()),
                ('ability', models.IntegerField()),
                ('magic', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('carga', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('cure', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('health', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('reputation', models.IntegerField()),
                ('Element', models.CharField(max_length=100)),
                ('background', models.TextField()),
                ('class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avatar.class')),
                ('idInventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avatar.inventoryitems')),
            ],
        ),
    ]
