# Generated by Django 4.2.1 on 2023-05-27 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avatar.inventoryitems')),
            ],
        ),
        migrations.AlterField(
            model_name='avatar',
            name='idInventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avatar.inventory'),
        ),
    ]
