# Generated by Django 4.2.1 on 2023-05-27 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0003_inventory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='idInventory',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='InventoryItems',
        ),
    ]
