# Generated by Django 4.2.1 on 2023-05-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0004_remove_avatar_idinventory_delete_inventory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='class',
            new_name='idClass',
        ),
    ]
