# Generated by Django 4.2.1 on 2023-05-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0005_rename_class_avatar_idclass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='AvatarClass',
        ),
        migrations.RenameField(
            model_name='avatar',
            old_name='idClass',
            new_name='avatarClass',
        ),
    ]
