# Generated by Django 4.2.1 on 2023-05-28 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0006_rename_class_avatarclass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='Element',
        ),
        migrations.AddField(
            model_name='avatar',
            name='avatarElement',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='avatar.avatarelement'),
            preserve_default=False,
        ),
    ]
