# Generated by Django 4.2.1 on 2023-05-27 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='avatar',
            new_name='idAvatar',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='item',
            new_name='idItem',
        ),
    ]
