# Generated by Django 4.2.1 on 2023-05-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_idavatar_inventory_avatar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitems',
            old_name='carga',
            new_name='load',
        ),
    ]
